// populateKnowledge.js
import sqlite3 from "sqlite3";
import { open } from "sqlite";
import { pipeline } from "@xenova/transformers";

async function populateKnowledge() {
  // Open existing database
  const db = await open({
    filename: "knowledge.db",
    driver: sqlite3.Database,
  });

  console.log("✅ Opened knowledge.db");

  // Load embedding model
  console.log("🧠 Loading embedding model...");
  const embedder = await pipeline("feature-extraction", "Xenova/all-MiniLM-L6-v2");
  console.log("✅ Embedding model loaded");

  // Prepare 100 farming entries (mix of short FAQs and detailed guides)
const entries = [
  { title: "Tomato Watering Schedule", content: "Water tomatoes 2–3 times per week depending on soil moisture. Ensure the soil is moist but not waterlogged.", category: "Crops", tags: "tomato, watering, irrigation" },
  { title: "Wheat Fertilizer Guidelines", content: "Apply 120:60:40 kg/ha of NPK fertilizer. Split nitrogen applications into 3 stages: basal, tillering, and panicle initiation.", category: "Crops", tags: "wheat, fertilizer, NPK" },
  { title: "Composting Basics", content: "Mix green materials (kitchen scraps, fresh grass) with brown materials (dry leaves, straw) in 3:1 ratio. Turn pile every 2 weeks. Ready in 3–6 months.", category: "Soil", tags: "compost, organic matter, soil" },
  { title: "Pest Control in Rice", content: "Monitor pests weekly. Use neem oil for organic control. Rotate pesticides to prevent resistance. Encourage natural predators like ladybugs.", category: "Pest Control", tags: "rice, pests, neem" },
  { title: "Drip Irrigation Benefits", content: "Drip irrigation saves 30–50% water and allows precise fertigation. Maintain 1.5–2 bar pressure. Suitable for vegetables, fruits, and cash crops.", category: "Irrigation", tags: "drip, irrigation, water" },
  { title: "Crop Rotation Importance", content: "Rotate crops yearly to improve soil structure, reduce pests, and maintain nutrients. Include legumes to fix nitrogen.", category: "Sustainable Farming", tags: "rotation, soil, legumes" },
  { title: "Organic Pest Control", content: "Use neem oil, trap crops, and beneficial insects to control pests organically.", category: "Pest Control", tags: "organic, pests, neem" },
  { title: "Mulching Advantages", content: "Mulch reduces evaporation, prevents weeds, and regulates soil temperature.", category: "Soil", tags: "mulch, soil, water conservation" },
  { title: "Seed Storage Tips", content: "Store seeds in a cool, dry place. Keep moisture below 10%. Label with variety and date.", category: "Crops", tags: "seeds, storage" },
  { title: "Fertilizer Timing", content: "Apply fertilizer based on soil test results and crop growth stage. Avoid applying before heavy rain.", category: "Soil", tags: "fertilizer, timing" },
  { title: "Potato Planting Depth", content: "Plant seed potatoes 10–15 cm deep with 30–40 cm spacing between plants.", category: "Crops", tags: "potato, planting, spacing" },
  { title: "Cucumber Trellising", content: "Use vertical trellises to save space, improve air circulation, and reduce disease.", category: "Crops", tags: "cucumber, trellis, growth" },
  { title: "Winter Wheat Sowing Time", content: "Sow winter wheat in October–November to optimize yield and avoid frost damage.", category: "Crops", tags: "wheat, sowing, winter" },
  { title: "Soil Testing Frequency", content: "Test soil at least once a year to monitor pH and nutrient levels.", category: "Soil", tags: "soil, testing, pH" },
  { title: "Green Manure Benefits", content: "Grow legumes or cover crops and plow them into soil to improve fertility and organic matter.", category: "Soil", tags: "green manure, organic, fertility" },
  { title: "Irrigation Scheduling", content: "Use soil moisture sensors and weather data to plan irrigation efficiently.", category: "Irrigation", tags: "water, irrigation, schedule" },
  { title: "Tomato Pruning Tips", content: "Remove suckers regularly to improve airflow, reduce disease, and increase fruit size.", category: "Crops", tags: "tomato, pruning, maintenance" },
  { title: "Rice Transplanting Method", content: "Transplant 20–25 day old seedlings in puddled fields maintaining 2–5 cm water level.", category: "Crops", tags: "rice, transplanting, irrigation" },
  { title: "Nitrogen Management in Maize", content: "Split nitrogen fertilizer in 2–3 applications: basal, V6 stage, and tasseling.", category: "Crops", tags: "maize, nitrogen, fertilizer" },
  { title: "Weed Management Strategies", content: "Use mulching, crop rotation, and targeted herbicides to control weeds effectively.", category: "Pest Control", tags: "weeds, control, herbicide" },
  { title: "Integrated Pest Management", content: "Combine biological, cultural, and chemical methods. Monitor pests and apply interventions only when thresholds are reached.", category: "Pest Control", tags: "IPM, pests, biological" },
  { title: "Tomato Disease Prevention", content: "Rotate crops, avoid overhead watering, and use resistant varieties to prevent fungal diseases.", category: "Pest Control", tags: "tomato, disease, prevention" },
  { title: "Vegetable Fertilizer Ratios", content: "Use NPK 10:10:10 balanced fertilizer, adjust based on soil tests and crop type.", category: "Crops", tags: "fertilizer, vegetables, NPK" },
  { title: "Potassium Importance", content: "Potassium improves root development, water uptake, and disease resistance.", category: "Soil", tags: "potassium, soil, nutrients" },
  { title: "Compost Tea Use", content: "Spray compost tea on leaves to provide nutrients and beneficial microbes.", category: "Soil", tags: "compost, foliar, microbes" },
  { title: "Mulch Material Selection", content: "Use straw, leaves, or plastic mulch depending on crop type and climate.", category: "Soil", tags: "mulch, material, soil" },
  { title: "Harvest Timing for Wheat", content: "Harvest when grains reach 12–14% moisture content to avoid losses.", category: "Crops", tags: "wheat, harvest, timing" },
  { title: "Corn Planting Density", content: "Plant 60–75 cm between rows and 20–30 cm between plants for optimal yield.", category: "Crops", tags: "corn, spacing, planting" },
  { title: "Soybean Inoculation", content: "Treat seeds with Rhizobium inoculant to improve nitrogen fixation.", category: "Crops", tags: "soybean, inoculant, nitrogen" },
  { title: "Mulch for Soil Moisture", content: "Apply organic mulch 5–10 cm thick to retain soil moisture.", category: "Soil", tags: "mulch, moisture, soil" },
  { title: "Frost Protection Techniques", content: "Use covers, windbreaks, or sprinklers to protect crops from frost.", category: "Weather", tags: "frost, protection, weather" },
  { title: "Crop Rotation for Legumes", content: "Rotate legumes with cereals to improve soil nitrogen and reduce disease.", category: "Sustainable Farming", tags: "rotation, legumes, soil" },
  { title: "Rainwater Harvesting", content: "Collect and store rainwater for irrigation during dry periods.", category: "Irrigation", tags: "water, rain, conservation" },
  { title: "Drip vs Sprinkler Irrigation", content: "Drip irrigation is more water-efficient; sprinklers are better for large fields.", category: "Irrigation", tags: "drip, sprinkler, irrigation" },
  { title: "Vegetable Companion Planting", content: "Plant basil with tomatoes to repel pests and enhance growth.", category: "Crops", tags: "companion planting, vegetables, pests" },
  { title: "Organic Fertilizers Options", content: "Use compost, manure, bone meal, or fish emulsion to supply nutrients.", category: "Soil", tags: "organic, fertilizer, soil" },
  { title: "Drip Line Maintenance", content: "Check drip lines regularly for clogs and leaks.", category: "Irrigation", tags: "drip, maintenance, irrigation" },
  { title: "Tomato Nutrient Deficiency", content: "Yellow leaves may indicate nitrogen deficiency; adjust fertilizer accordingly.", category: "Crops", tags: "tomato, nutrients, deficiency" },
  { title: "Greenhouse Temperature Control", content: "Use fans, shading, or heaters to maintain 20–25°C for optimal growth.", category: "Technology", tags: "greenhouse, temperature, control" },
  { title: "Farm Machinery Safety", content: "Always read manuals, wear protective gear, and follow safety protocols.", category: "Safety", tags: "machinery, safety, equipment" },
  { title: "Cucumber Disease Prevention", content: "Rotate crops, avoid water splash on leaves, and remove infected plants promptly.", category: "Pest Control", tags: "cucumber, disease, prevention" },
  { title: "Soil pH Adjustment", content: "Use lime for acidic soil and sulfur/gypsum for alkaline soil to maintain pH 6–7.", category: "Soil", tags: "pH, soil, adjustment" },
  { title: "Vegetable Harvest Indicators", content: "Harvest when fruits reach full size, color, and firmness.", category: "Crops", tags: "vegetables, harvest, timing" },
  { title: "Mulch Benefits Overview", content: "Conserves moisture, regulates temperature, suppresses weeds, and improves soil.", category: "Soil", tags: "mulch, benefits, soil" },
  { title: "Compost Application Rate", content: "Apply 2–4 tons per hectare annually depending on soil fertility.", category: "Soil", tags: "compost, application, soil" },
  { title: "Crop Disease Early Signs", content: "Look for leaf spots, discoloration, wilting, or abnormal growth.", category: "Pest Control", tags: "disease, early signs, crops" },
  { title: "Farm Record Keeping", content: "Maintain logs of planting dates, inputs, yields, and weather observations.", category: "Management", tags: "records, management, farm" },
  { title: "Soil Moisture Monitoring", content: "Use tensiometers or soil probes to monitor moisture levels accurately.", category: "Irrigation", tags: "soil, moisture, monitoring" },
  { title: "Pest Identification Guide", content: "Learn to identify pests visually or using reference guides before control measures.", category: "Pest Control", tags: "pests, identification, guide" },
  { title: "Herbicide Application Tips", content: "Apply during calm weather, follow label instructions, and avoid drift.", category: "Pest Control", tags: "herbicide, application, safety" },
  { title: "Cover Crop Benefits", content: "Prevent erosion, improve fertility, suppress weeds, and enhance soil structure.", category: "Sustainable Farming", tags: "cover crop, soil, fertility" },
  { title: "Seed Germination Test", content: "Place 100 seeds on moist paper, count sprouted seeds to check viability.", category: "Crops", tags: "seeds, germination, test" },
  { title: "Tomato Pest Monitoring", content: "Inspect leaves weekly for aphids, whiteflies, and other pests.", category: "Pest Control", tags: "tomato, pests, monitoring" },
  { title: "Vegetable Green Manure", content: "Plant cover crops to improve nitrogen and organic matter in the soil.", category: "Soil", tags: "green manure, crops, soil" },
  { title: "Irrigation Pressure Check", content: "Regularly check pump and drip pressure to ensure uniform water distribution.", category: "Irrigation", tags: "pressure, irrigation, check" },
  { title: "Fertilizer Storage Safety", content: "Store fertilizers in a dry, cool place away from children and animals.", category: "Safety", tags: "fertilizer, storage, safety" },
  { title: "Winter Crop Protection", content: "Use row covers, mulch, and windbreaks to protect crops from frost.", category: "Weather", tags: "winter, frost, protection" },
  { title: "Seedling Transplant Care", content: "Harden seedlings before transplanting; water lightly and avoid stress.", category: "Crops", tags: "seedlings, transplant, care" },
  { title: "Pest Biological Control", content: "Introduce beneficial insects like ladybugs or lacewings to reduce pest populations.", category: "Pest Control", tags: "biological, pest control, insects" },
  { title: "Soil Aeration Techniques", content: "Use tillage, spading, or aerators to improve soil structure and root growth.", category: "Soil", tags: "aeration, soil, structure" },
  { title: "Tomato Harvest Timing", content: "Harvest when fruits are firm, fully colored, and slightly soft at the blossom end.", category: "Crops", tags: "tomato, harvest, timing" },
  { title: "Rice Grain Drying", content: "Dry harvested rice to 12–14% moisture content to prevent mold and spoilage.", category: "Crops", tags: "rice, drying, harvest" },
  { title: "Maize Planting Depth", content: "Plant seeds 4–6 cm deep for proper emergence and root development.", category: "Crops", tags: "maize, planting, depth" },
  { title: "Irrigation Water Quality", content: "Use clean water free of salts and debris to avoid clogging and plant damage.", category: "Irrigation", tags: "water, quality, irrigation" },
  { title: "Soil Nutrient Testing", content: "Analyze NPK, pH, and organic matter before applying fertilizers.", category: "Soil", tags: "soil, testing, nutrients" },
  { title: "Vegetable Pest Traps", content: "Use yellow sticky traps to monitor and reduce flying pests.", category: "Pest Control", tags: "vegetable, traps, pests" },
  { title: "Tomato Spacing Guidelines", content: "Maintain 50–60 cm between plants and 80–100 cm between rows.", category: "Crops", tags: "tomato, spacing, planting" },
  { title: "Corn Fertilizer Schedule", content: "Split nitrogen into basal, side dressing, and tasseling stages.", category: "Crops", tags: "corn, fertilizer, schedule" },
  { title: "Greenhouse Irrigation", content: "Use drip or micro-sprinklers to maintain soil moisture without wetting foliage.", category: "Irrigation", tags: "greenhouse, irrigation, drip" },
  { title: "Weed Mulching Techniques", content: "Apply organic mulch 5–10 cm thick to suppress weeds effectively.", category: "Soil", tags: "mulch, weeds, soil" },
  { title: "Potato Fertilizer Guidelines", content: "Apply 80:60:60 kg/ha NPK at planting and side dress 3–4 weeks after emergence.", category: "Crops", tags: "potato, fertilizer, NPK" },
  { title: "Cabbage Spacing", content: "Plant cabbage 30–40 cm apart with 50–60 cm between rows.", category: "Crops", tags: "cabbage, spacing, planting" },
  { title: "Carrot Thinning", content: "Thin seedlings to 3–5 cm apart to avoid crowding and ensure root development.", category: "Crops", tags: "carrot, thinning, planting" },
  { title: "Tomato Blossom End Rot Prevention", content: "Maintain consistent soil moisture and provide adequate calcium through fertilization.", category: "Crops", tags: "tomato, calcium, disease" },
  { title: "Rice Nitrogen Timing", content: "Split nitrogen applications at basal, tillering, and panicle initiation stages.", category: "Crops", tags: "rice, nitrogen, timing" },
  { title: "Maize Irrigation Requirements", content: "Provide 500–700 mm water during growing season depending on rainfall and soil type.", category: "Irrigation", tags: "maize, irrigation, water" },
  { title: "Wheat Disease Monitoring", content: "Inspect fields weekly for rust, smut, and leaf blight; apply fungicide if needed.", category: "Pest Control", tags: "wheat, disease, monitoring" },
  { title: "Vegetable Fertigation", content: "Apply soluble fertilizers through drip irrigation based on soil test recommendations.", category: "Irrigation", tags: "vegetable, fertigation, irrigation" },
  { title: "Organic Soil Amendments", content: "Incorporate compost, manure, and biochar to improve soil fertility.", category: "Soil", tags: "organic, soil, amendments" },
  { title: "Cucumber Spacing", content: "Plant cucumbers 30–50 cm apart and 1–1.5 m between rows.", category: "Crops", tags: "cucumber, spacing, planting" },
  { title: "Tomato Mulching Technique", content: "Apply straw or plastic mulch to conserve moisture and control weeds.", category: "Soil", tags: "tomato, mulch, soil" },
  { title: "Corn Irrigation Scheduling", content: "Use tensiometers or soil probes to irrigate when soil moisture falls below 50% field capacity.", category: "Irrigation", tags: "corn, irrigation, schedule" },
  { title: "Soybean Planting Depth", content: "Plant seeds 3–5 cm deep depending on soil type and moisture.", category: "Crops", tags: "soybean, planting, depth" },
  { title: "Vegetable Pest Cultural Practices", content: "Rotate crops, remove crop residues, and maintain field sanitation to prevent pests.", category: "Pest Control", tags: "vegetable, pests, cultural" },
  { title: "Potato Disease Control", content: "Use certified seed, rotate fields, and apply fungicides when needed.", category: "Pest Control", tags: "potato, disease, control" },
  { title: "Drip Irrigation Maintenance", content: "Flush lines monthly and check emitters to prevent blockages.", category: "Irrigation", tags: "drip, maintenance, irrigation" },
  { title: "Tomato Fertilizer Schedule", content: "Apply NPK 20:20:20 at planting and side dress every 3–4 weeks.", category: "Crops", tags: "tomato, fertilizer, schedule" },
  { title: "Rice Weed Management", content: "Hand weed or use pre-emergence herbicides within first 45 days.", category: "Pest Control", tags: "rice, weed, management" },
  { title: "Corn Pest Monitoring", content: "Scout for stem borers and armyworms; use pheromone traps or natural predators.", category: "Pest Control", tags: "corn, pests, monitoring" },
  { title: "Fertilizer Application Safety", content: "Wear gloves and mask when handling fertilizers; avoid over-application.", category: "Safety", tags: "fertilizer, safety, application" },
  { title: "Seedling Hardening Process", content: "Expose seedlings to outdoor conditions gradually before transplanting.", category: "Crops", tags: "seedlings, hardening, transplant" },
  { title: "Soil Compaction Prevention", content: "Avoid working soil when wet and use cover crops to improve structure.", category: "Soil", tags: "compaction, soil, prevention" },
  { title: "Vegetable Disease Monitoring", content: "Check leaves and stems regularly for spots, discoloration, or wilting.", category: "Pest Control", tags: "vegetable, disease, monitoring" },
  { title: "Tomato Trellis Support", content: "Use stakes or cages to support growth and prevent fruit contact with soil.", category: "Crops", tags: "tomato, trellis, support" },
  { title: "Crop Residue Management", content: "Incorporate or remove crop residues to manage nutrients and pests.", category: "Sustainable Farming", tags: "residue, management, crops" },
  { title: "Irrigation Efficiency Measurement", content: "Measure applied water vs. crop requirement to improve irrigation efficiency.", category: "Irrigation", tags: "efficiency, irrigation, measurement" },
  { title: "Fertilizer Calibration", content: "Calibrate spreaders and sprayers to ensure correct fertilizer application.", category: "Soil", tags: "fertilizer, calibration, application" },
  { title: "Pest Trap Placement", content: "Place sticky traps at canopy level for effective monitoring.", category: "Pest Control", tags: "traps, placement, monitoring" },
  { title: "Compost Turning Frequency", content: "Turn compost pile every 2 weeks to maintain aeration and decomposition.", category: "Soil", tags: "compost, turning, aeration" },
  { title: "Vegetable Seed Treatment", content: "Treat seeds with fungicides or hot water to prevent early diseases.", category: "Pest Control", tags: "vegetable, seeds, treatment" },
  { title: "Cabbage Pest Control", content: "Monitor for cabbage worms and use row covers or biological controls.", category: "Pest Control", tags: "cabbage, pests, control" },
  { title: "Tomato Irrigation Frequency", content: "Irrigate every 3–4 days, more often in dry, hot weather.", category: "Irrigation", tags: "tomato, irrigation, frequency" },
  { title: "Wheat Sowing Seed Rate", content: "Use 100–125 kg seeds per hectare depending on variety and soil fertility.", category: "Crops", tags: "wheat, seed rate, sowing" },
  { title: "Vegetable Mulch Thickness", content: "Apply 5–10 cm mulch layer depending on soil type and climate.", category: "Soil", tags: "vegetables, mulch, soil" },
  { title: "Rice Drainage Practice", content: "Drain water gradually after panicle initiation to reduce lodging and disease.", category: "Irrigation", tags: "rice, drainage, irrigation" },
  { title: "Potato Water Management", content: "Irrigate 2–3 times per week; avoid waterlogging and drought stress.", category: "Irrigation", tags: "potato, water, management" },
  { title: "Crop Disease Resistant Varieties", content: "Select varieties resistant to common diseases in your region.", category: "Pest Control", tags: "disease, resistant, crops" },
  { title: "Vegetable Fertilizer Frequency", content: "Split fertilizer applications every 3–4 weeks during active growth.", category: "Soil", tags: "vegetable, fertilizer, frequency" },
  { title: "Tomato Pruning Frequency", content: "Prune lateral shoots weekly during active growth to improve airflow.", category: "Crops", tags: "tomato, pruning, frequency" },
  { title: "Corn Harvest Moisture", content: "Harvest at 20–25% moisture for safe storage.", category: "Crops", tags: "corn, harvest, moisture" },
  { title: "Soil Organic Carbon Maintenance", content: "Add compost and reduce tillage to maintain organic carbon levels.", category: "Soil", tags: "organic, carbon, soil" },
  { title: "Rice Nitrogen Use Efficiency", content: "Split applications and use slow-release fertilizers to reduce losses.", category: "Crops", tags: "rice, nitrogen, efficiency" },
  { title: "Maize Harvest Indicators", content: "Harvest when kernels are hard and cob moisture is 20–25%.", category: "Crops", tags: "maize, harvest, indicators" },
  { title: "Vegetable Frost Protection", content: "Use covers, cloches, or row tunnels to protect from frost.", category: "Weather", tags: "vegetable, frost, protection" },
  { title: "Drip Irrigation Layout", content: "Install mainline, sub-main, and lateral lines for uniform water delivery.", category: "Irrigation", tags: "drip, layout, irrigation" },
  { title: "Tomato Yellow Leaf Prevention", content: "Maintain balanced nutrition and avoid overwatering.", category: "Crops", tags: "tomato, leaf, nutrients" },
  { title: "Cover Crop Species Selection", content: "Use legumes, grasses, or brassicas depending on soil improvement goals and climate.", category: "Sustainable Farming", tags: "cover crop, species, soil" },
  { title: "Vegetable Spacing Guidelines", content: "Follow recommended spacing for each crop to ensure proper growth and airflow.", category: "Crops", tags: "vegetable, spacing, planting" },
  { title: "Compost Maturity Test", content: "Check for dark color, earthy smell, and no recognizable raw materials before application.", category: "Soil", tags: "compost, maturity, testing" },
  { title: "Rice Seedling Hardening", content: "Expose seedlings gradually to sun and wind before transplanting to improve survival.", category: "Crops", tags: "rice, seedlings, hardening" },
  { title: "Potato Late Blight Prevention", content: "Use resistant varieties, rotate fields, and apply fungicides when needed.", category: "Pest Control", tags: "potato, late blight, prevention" },
  { title: "Cucumber Fertilizer Schedule", content: "Apply 80:60:60 kg/ha NPK; side dress every 3–4 weeks during active growth.", category: "Crops", tags: "cucumber, fertilizer, schedule" },
  { title: "Tomato Disease Scouting", content: "Inspect fields twice weekly for early detection of diseases.", category: "Pest Control", tags: "tomato, disease, scouting" },
  { title: "Maize Irrigation Depth", content: "Apply 25–30 mm per irrigation depending on soil moisture and weather.", category: "Irrigation", tags: "maize, irrigation, depth" },
  { title: "Vegetable Foliar Fertilization", content: "Apply micronutrients as foliar sprays during deficiency symptoms.", category: "Soil", tags: "vegetable, foliar, fertilization" },
  { title: "Greenhouse Irrigation Automation", content: "Use sensors and timers to optimize water delivery and reduce waste.", category: "Technology", tags: "greenhouse, irrigation, automation" },
  { title: "Tomato Fruit Thinning", content: "Remove excess flowers or small fruits to improve size and quality.", category: "Crops", tags: "tomato, thinning, fruit" },
  { title: "Soil Salinity Management", content: "Leach salts with excess irrigation, improve drainage, and use salt-tolerant crops.", category: "Soil", tags: "salinity, soil, management" },
  { title: "Vegetable Pest Thresholds", content: "Monitor pest population and apply control measures only when thresholds are reached.", category: "Pest Control", tags: "vegetable, pests, thresholds" },
  { title: "Potato Hilling Technique", content: "Hill soil around stems 3–4 times during growing season to protect tubers and improve yield.", category: "Crops", tags: "potato, hilling, technique" },
  { title: "Rice Water Management Efficiency", content: "Use alternate wetting and drying to save water and maintain yield.", category: "Irrigation", tags: "rice, water, efficiency" },
  { title: "Tomato Green Manure Use", content: "Incorporate legume residues into soil to improve fertility and structure.", category: "Soil", tags: "tomato, green manure, soil" },
  { title: "Corn Nitrogen Split Application", content: "Apply nitrogen at planting, V6 stage, and tasseling for maximum uptake.", category: "Crops", tags: "corn, nitrogen, split" },
  { title: "Vegetable Pest Biological Control", content: "Release ladybugs, lacewings, or parasitoids to reduce pest populations naturally.", category: "Pest Control", tags: "vegetable, biological, control" },
  { title: "Cucumber Trellis Height", content: "Use 1.5–2 m trellises to allow vertical growth and better air circulation.", category: "Crops", tags: "cucumber, trellis, height" },
  { title: "Compost Moisture Maintenance", content: "Maintain 50–60% moisture by watering or turning pile as needed.", category: "Soil", tags: "compost, moisture, maintenance" },
  { title: "Vegetable Irrigation Frequency", content: "Adjust based on soil type, crop stage, and weather conditions.", category: "Irrigation", tags: "vegetable, irrigation, frequency" },
  { title: "Tomato Blossom Removal", content: "Remove extra blossoms to improve fruit size and prevent nutrient stress.", category: "Crops", tags: "tomato, blossoms, removal" },
  { title: "Corn Plant Nutrition Monitoring", content: "Observe leaf color and growth; adjust fertilization accordingly.", category: "Soil", tags: "corn, nutrition, monitoring" },
  { title: "Rice Field Drainage Timing", content: "Drain 7–10 days before harvest to improve grain quality and reduce lodging.", category: "Irrigation", tags: "rice, drainage, timing" },
  { title: "Potato Disease Resistant Cultivars", content: "Use varieties resistant to blight, scab, and nematodes for better yield.", category: "Pest Control", tags: "potato, resistant, cultivars" },
  { title: "Vegetable Greenhouse Ventilation", content: "Ensure adequate airflow to reduce humidity and prevent disease.", category: "Technology", tags: "greenhouse, ventilation, vegetable" },
  { title: "Tomato Fruit Color Monitoring", content: "Harvest when fruits reach uniform red color for best quality.", category: "Crops", tags: "tomato, fruit, color" },
  { title: "Maize Irrigation Water Use", content: "Apply water according to crop evapotranspiration to prevent waste.", category: "Irrigation", tags: "maize, water, use" },
  { title: "Rice Weed Control Cultural Practices", content: "Use crop rotation, proper spacing, and stale seedbed to reduce weeds.", category: "Pest Control", tags: "rice, weed, cultural" },
  { title: "Vegetable Mulch Decomposition", content: "Monitor organic mulch decomposition and reapply when necessary.", category: "Soil", tags: "vegetable, mulch, decomposition" },
  { title: "Tomato Disease Resistant Hybrids", content: "Select hybrids with resistance to fusarium, verticillium, and tomato mosaic virus.", category: "Pest Control", tags: "tomato, resistant, hybrids" },
  { title: "Corn Root Health", content: "Avoid compacted soils, maintain proper irrigation, and rotate crops.", category: "Soil", tags: "corn, roots, health" },
  { title: "Vegetable Frost Tolerance", content: "Use frost-resistant varieties or cover plants to prevent cold damage.", category: "Weather", tags: "vegetable, frost, tolerance" },
  { title: "Rice Fertilizer Application Method", content: "Apply fertilizers in small splits directly to the root zone for efficiency.", category: "Crops", tags: "rice, fertilizer, method" },
  { title: "Cucumber Disease Early Signs", content: "Look for yellow spots, wilting, or leaf curl to detect disease early.", category: "Pest Control", tags: "cucumber, disease, early signs" },
  { title: "Potato Soil Testing Frequency", content: "Test soil annually for pH, nitrogen, phosphorus, and potassium levels.", category: "Soil", tags: "potato, soil, testing" },
  { title: "Vegetable Harvest Frequency", content: "Harvest regularly to improve yield and prevent overripe produce.", category: "Crops", tags: "vegetable, harvest, frequency" },
  { title: "Tomato Water Stress Signs", content: "Curling leaves, blossom drop, and poor fruit set indicate water stress.", category: "Crops", tags: "tomato, water, stress" },
  { title: "Corn Lodging Prevention", content: "Maintain proper spacing, support, and nutrient balance to reduce lodging.", category: "Crops", tags: "corn, lodging, prevention" },
  { title: "Rice Fertilizer Efficiency", content: "Use soil tests and split applications to improve nutrient uptake.", category: "Soil", tags: "rice, fertilizer, efficiency" },
  { title: "Vegetable Pollination Support", content: "Introduce bees or hand pollinate flowers for better fruit set.", category: "Crops", tags: "vegetable, pollination, support" },
  { title: "Drip System Pressure Regulation", content: "Maintain 1.5–2 bar pressure to prevent emitter damage and uniform water distribution.", category: "Irrigation", tags: "drip, pressure, regulation" },
  { title: "Tomato Crop Rotation Benefits", content: "Avoid growing tomatoes consecutively in same soil to reduce disease and nutrient depletion.", category: "Sustainable Farming", tags: "tomato, rotation, benefits" },
  { title: "Potato Nitrogen Use", content: "Split nitrogen into 2–3 applications to maximize uptake and minimize leaching.", category: "Soil", tags: "potato, nitrogen, use" },
  { title: "Vegetable Pest Monitoring Frequency", content: "Inspect crops twice weekly to catch early infestations.", category: "Pest Control", tags: "vegetable, monitoring, pests" },
  { title: "Rice Seed Germination Test", content: "Test 100 seeds on moist paper; count sprouted seeds to estimate viability.", category: "Crops", tags: "rice, seeds, germination" },
  { title: "Corn Disease Prevention", content: "Rotate fields, use resistant varieties, and monitor for early symptoms.", category: "Pest Control", tags: "corn, disease, prevention" },
  { title: "Vegetable Fertilizer Record Keeping", content: "Maintain logs of fertilizer type, rate, and date for better crop management.", category: "Management", tags: "vegetable, records, fertilizer" },
  { title: "Tomato Harvest Indicators", content: "Harvest when fruits reach uniform size, color, and firmness.", category: "Crops", tags: "tomato, harvest, indicators" },
  { title: "Soil Aeration Practices", content: "Use reduced tillage, cover crops, and organic matter to maintain aeration.", category: "Soil", tags: "soil, aeration, practices" },
  { title: "Corn Irrigation Scheduling", content: "Apply water according to crop stage and soil moisture to optimize growth.", category: "Irrigation", tags: "corn, irrigation, schedule" },
  { title: "Tomato Mulching Practices", content: "Apply 5–10 cm thick organic mulch to retain moisture and suppress weeds.", category: "Soil", tags: "tomato, mulch, soil" },
  { title: "Potato Pest Scouting", content: "Inspect plants twice a week for signs of aphids, beetles, and blight.", category: "Pest Control", tags: "potato, scouting, pests" },
  { title: "Vegetable Crop Rotation Planning", content: "Rotate crops to improve soil fertility and reduce disease buildup.", category: "Sustainable Farming", tags: "vegetable, rotation, planning" },
  { title: "Rice Nitrogen Efficiency", content: "Split nitrogen application and use urea deep placement for better uptake.", category: "Soil", tags: "rice, nitrogen, efficiency" },
  { title: "Greenhouse Irrigation Tips", content: "Check moisture sensors regularly and adjust irrigation schedule as needed.", category: "Technology", tags: "greenhouse, irrigation, tips" },
  { title: "Cucumber Pest Thresholds", content: "Apply interventions only when pest populations reach economic threshold levels.", category: "Pest Control", tags: "cucumber, pests, threshold" },
  { title: "Vegetable Seedling Transplanting", content: "Transplant seedlings when they have 2–4 true leaves for best establishment.", category: "Crops", tags: "vegetable, transplanting, seedlings" },
  { title: "Tomato Fertilizer Side Dressing", content: "Apply nitrogen-rich fertilizer at mid-growth to boost fruit set and size.", category: "Soil", tags: "tomato, fertilizer, side dressing" },
  { title: "Rice Harvest Moisture Management", content: "Harvest at 20–25% moisture; dry to 12–14% for storage.", category: "Crops", tags: "rice, harvest, moisture" },
  { title: "Corn Growth Stage Monitoring", content: "Track stages like V6, tasseling, and silking for timely management.", category: "Crops", tags: "corn, growth, monitoring" },
  { title: "Vegetable Frost Cover Materials", content: "Use fabric row covers or plastic sheets to protect crops from frost.", category: "Weather", tags: "vegetable, frost, cover" },
  { title: "Potato Irrigation Method", content: "Use furrow or drip irrigation to ensure uniform moisture without waterlogging.", category: "Irrigation", tags: "potato, irrigation, method" },
  { title: "Tomato Pruning Frequency", content: "Prune suckers weekly to maintain plant structure and airflow.", category: "Crops", tags: "tomato, pruning, frequency" },
  { title: "Rice Weed Identification", content: "Identify common weeds like barnyard grass and sedges for targeted control.", category: "Pest Control", tags: "rice, weed, identification" },
  { title: "Vegetable Fertilizer Split Timing", content: "Apply fertilizers in splits to match crop demand and minimize losses.", category: "Soil", tags: "vegetable, fertilizer, timing" },
  { title: "Corn Pest Biological Controls", content: "Introduce natural predators like ladybugs or predatory mites to reduce pest pressure.", category: "Pest Control", tags: "corn, biological, control" },
  { title: "Potato Soil pH Range", content: "Maintain pH 5.5–6.5 for optimal nutrient availability and yield.", category: "Soil", tags: "potato, pH, soil" },
  { title: "Vegetable Companion Plants", content: "Plant basil with tomatoes, marigold with cucumbers to reduce pests.", category: "Crops", tags: "vegetable, companion, planting" },
  { title: "Tomato Irrigation Frequency", content: "Water 2–3 times per week, adjusting for rainfall and soil type.", category: "Irrigation", tags: "tomato, irrigation, frequency" },
  { title: "Rice Disease Early Detection", content: "Monitor leaves for yellowing or spotting to apply control early.", category: "Pest Control", tags: "rice, disease, early detection" },
  { title: "Corn Fertilizer Rate Adjustment", content: "Adjust fertilizer rates based on soil tests and previous crop residues.", category: "Soil", tags: "corn, fertilizer, adjustment" },
  { title: "Vegetable Crop Scheduling", content: "Plan planting dates to ensure continuous harvest and avoid pest overlaps.", category: "Management", tags: "vegetable, scheduling, management" },
  { title: "Potato Tuber Spacing", content: "Maintain 30–40 cm between tubers to maximize growth and yield.", category: "Crops", tags: "potato, spacing, tubers" },
  { title: "Tomato Blossom Drop Causes", content: "Caused by high temperature, water stress, or nutrient imbalance.", category: "Crops", tags: "tomato, blossom, drop" },
  { title: "Rice Field Leveling Importance", content: "Level fields to ensure uniform water distribution and reduce weed growth.", category: "Irrigation", tags: "rice, leveling, field" },
  { title: "Vegetable Pest Life Cycle Knowledge", content: "Understanding pest life cycles helps time control interventions effectively.", category: "Pest Control", tags: "vegetable, pests, lifecycle" },
  { title: "Corn Nitrogen Deficiency Signs", content: "Yellowing of older leaves indicates nitrogen deficiency; supplement as needed.", category: "Soil", tags: "corn, nitrogen, deficiency" },
  { title: "Potato Harvest Indicators", content: "Harvest when foliage dies back and tubers reach desired size.", category: "Crops", tags: "potato, harvest, indicators" },
  { title: "Tomato Leaf Curl Management", content: "Avoid overwatering, maintain nutrient balance, and use resistant varieties.", category: "Pest Control", tags: "tomato, leaf curl, management" },
  { title: "Rice Drainage Before Harvest", content: "Drain water 7–10 days prior to harvest to improve grain quality.", category: "Irrigation", tags: "rice, drainage, harvest" },
  { title: "Vegetable Mulch Renewal", content: "Replace decomposed mulch every 4–6 weeks for consistent benefits.", category: "Soil", tags: "vegetable, mulch, renewal" },
  { title: "Corn Pollination Monitoring", content: "Ensure silk emergence coincides with pollen shed for good kernel set.", category: "Crops", tags: "corn, pollination, monitoring" },
  { title: "Potato Sprout Chitting", content: "Allow seed potatoes to sprout in light before planting to speed establishment.", category: "Crops", tags: "potato, sprouting, chitting" },
  { title: "Tomato Disease Spray Timing", content: "Apply fungicides early in disease development for better control.", category: "Pest Control", tags: "tomato, disease, spray" },
  { title: "Rice Fertilizer Application Depth", content: "Place fertilizers near the root zone for efficient uptake.", category: "Soil", tags: "rice, fertilizer, depth" },
  { title: "Vegetable Harvest Handling", content: "Handle carefully to reduce bruising and maintain quality.", category: "Crops", tags: "vegetable, harvest, handling" },
  { title: "Corn Irrigation Efficiency Monitoring", content: "Use soil moisture sensors and crop evapotranspiration data to adjust irrigation.", category: "Irrigation", tags: "corn, irrigation, efficiency" },
  { title: "Potato Disease Resistant Seed", content: "Use certified seed to reduce incidence of diseases like blight.", category: "Pest Control", tags: "potato, seed, resistant" },
  { title: "Tomato Trellis Support", content: "Provide vertical support for vining varieties to improve fruit quality.", category: "Crops", tags: "tomato, trellis, support" },
  { title: "Vegetable Fertilizer Storage", content: "Store fertilizers in a dry, cool, and ventilated area to maintain efficacy.", category: "Soil", tags: "vegetable, fertilizer, storage" },
  { title: "Rice Pest Scouting Frequency", content: "Scout fields twice weekly to detect pests early and take timely action.", category: "Pest Control", tags: "rice, scouting, pests" },
  { title: "Corn Frost Protection", content: "Cover seedlings or use heaters during unexpected cold snaps.", category: "Weather", tags: "corn, frost, protection" },
  { title: "Tomato Nutrient Spray Schedule", content: "Apply foliar sprays of micronutrients as needed based on deficiency symptoms.", category: "Soil", tags: "tomato, nutrients, spray" },
  { title: "Vegetable Plant Density Adjustment", content: "Adjust spacing based on growth habit and fertility to avoid competition.", category: "Crops", tags: "vegetable, density, adjustment" },
  { title: "Potato Weed Control Methods", content: "Use mechanical weeding, mulching, and selective herbicides to manage weeds.", category: "Pest Control", tags: "potato, weeds, control" },
  { title: "Rice Seedling Age for Transplanting", content: "Transplant seedlings aged 20–25 days for optimal establishment.", category: "Crops", tags: "rice, seedlings, transplanting" },
  { title: "Corn Soil Fertility Management", content: "Incorporate organic matter, monitor nutrients, and rotate crops.", category: "Soil", tags: "corn, fertility, management" },
  { title: "Vegetable Disease Identification", content: "Learn symptoms like spots, wilting, and discoloration to identify diseases early.", category: "Pest Control", tags: "vegetable, disease, identification" },
  { title: "Tomato Irrigation Scheduling Tools", content: "Use tensiometers or drip sensors to schedule irrigation precisely.", category: "Irrigation", tags: "tomato, irrigation, scheduling" },
  { title: "Potato Fertilizer Application Timing", content: "Split applications during vegetative growth and tuber formation for efficiency.", category: "Soil", tags: "potato, fertilizer, timing" },
  { title: "Rice Disease Resistant Varieties", content: "Select high-yield varieties resistant to blast and bacterial leaf blight.", category: "Pest Control", tags: "rice, resistant, varieties" },
  { title: "Vegetable Pollination Techniques", content: "Use hand pollination or introduce bees in greenhouses to ensure fruit set.", category: "Crops", tags: "vegetable, pollination, techniques" },
  { title: "Corn Mulch Benefits", content: "Mulch conserves moisture, reduces weeds, and moderates soil temperature.", category: "Soil", tags: "corn, mulch, benefits" },
  { title: "Tomato Pest Resistance Strategies", content: "Rotate crops, select resistant varieties, and encourage beneficial insects.", category: "Pest Control", tags: "tomato, resistance, pests" },
  { title: "Vegetable Harvest Timing Indicators", content: "Observe color, size, and firmness to determine optimal harvest time.", category: "Crops", tags: "vegetable, harvest, timing" },
  { title: "Potato Irrigation Scheduling", content: "Apply water based on soil moisture, weather, and growth stage.", category: "Irrigation", tags: "potato, irrigation, scheduling" },
  { title: "Rice Crop Residue Management", content: "Incorporate straw into soil or use for mulch to improve soil organic matter.", category: "Soil", tags: "rice, residue, management" },
  { title: "Corn Pest Early Warning", content: "Monitor fields regularly for signs of pests to enable timely interventions.", category: "Pest Control", tags: "corn, pests, warning" },
  { title: "Vegetable Fertilizer Efficiency Tips", content: "Apply at correct rate, split applications, and monitor crop response.", category: "Soil", tags: "vegetable, fertilizer, efficiency" },
  { title: "Tomato Greenhouse Ventilation Rate", content: "Maintain airflow to reduce humidity and prevent fungal diseases.", category: "Technology", tags: "tomato, greenhouse, ventilation" },
  { title: "Potato Harvest Storage Conditions", content: "Store at 4–10°C with 90–95% humidity to prevent sprouting and decay.", category: "Crops", tags: "potato, harvest, storage" },
  { title: "Rice Water-Saving Techniques", content: "Use alternate wetting and drying or drip irrigation to conserve water.", category: "Irrigation", tags: "rice, water-saving, techniques" },
  { title: "Vegetable Disease Forecasting Tools", content: "Use weather-based models to predict disease outbreaks and plan control.", category: "Pest Control", tags: "vegetable, forecasting, disease" }
];


  // Generate embeddings and insert
  for (let i = 0; i < entries.length; i++) {
    const entry = entries[i];
    try {
      const embedding = await embedder(entry.content, { pooling: "mean", normalize: true });
      const vector = Buffer.from(new Float32Array(embedding.data).buffer);

      await db.run(
        `INSERT INTO knowledge (title, content, category, tags, embedding) VALUES (?, ?, ?, ?, ?)`,
        [entry.title, entry.content, entry.category, entry.tags, vector]
      );
      console.log(`✅ Inserted: ${entry.title} (${i + 1}/${entries.length})`);
    } catch (err) {
      console.error(`❌ Error inserting ${entry.title}:`, err);
    }
  }

  console.log("🌱 All entries inserted successfully!");
  await db.close();
}

populateKnowledge();